name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Chạy tự động mỗi khi có code mới đẩy lên nhánh master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cài đặt thư viện
        run: npm install

      - name: Biên dịch dự án (Build)
        run: npm run build

      - name: Upload kết quả
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Triển khai lên Web
        uses: actions/deploy-pages@v4
